{
  "formatVersion": "1.1",
  "component": {
    "group": "net.blueid",
    "module": "access",
    "version": "5.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.4"
    }
  },
  "variants": [
    {
      "name": "releaseApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.9.22"
          }
        }
      ],
      "files": [
        {
          "name": "access-5.0.aar",
          "url": "access-5.0.aar",
          "size": 2819279,
          "sha512": "bba1a9d60a2d7dc2f695b08198c476b4c733688c3dfbbf1c3a12a167eebf3cb4fcbed4f4704dcbc680b9b330d79bce0be78307b9f79d9a5e7f1e768cc68c9b8c",
          "sha256": "ce9c1755d2b793e4f70df0928aebbcdfd1d6d6b6cf29c30cf03a045f14bfb4f8",
          "sha1": "664998562362344886ca10d23a6f25e437b84bd0",
          "md5": "943c28e26963facd5dee9e9c20699baf"
        }
      ]
    },
    {
      "name": "releaseRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "androidx.room",
          "module": "room-runtime",
          "version": {
            "requires": "2.6.1"
          }
        },
        {
          "group": "com.google.android.material",
          "module": "material",
          "version": {
            "requires": "1.11.0"
          }
        },
        {
          "group": "androidx.room",
          "module": "room-ktx",
          "version": {
            "requires": "2.6.1"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.6.1"
          }
        },
        {
          "group": "com.squareup.retrofit2",
          "module": "retrofit",
          "version": {
            "requires": "2.9.0"
          }
        },
        {
          "group": "com.squareup.retrofit2",
          "module": "converter-scalars",
          "version": {
            "requires": "2.9.0"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "logging-interceptor",
          "version": {
            "requires": "4.11.0"
          }
        },
        {
          "group": "com.jakewharton.retrofit",
          "module": "retrofit2-kotlinx-serialization-converter",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "no.nordicsemi.android",
          "module": "dfu",
          "version": {
            "requires": "2.4.2"
          }
        },
        {
          "group": "no.nordicsemi.android.kotlin.ble",
          "module": "scanner",
          "version": {
            "requires": "1.0.13"
          }
        },
        {
          "group": "no.nordicsemi.android.kotlin.ble",
          "module": "client",
          "version": {
            "requires": "1.0.13"
          }
        },
        {
          "group": "com.google.protobuf",
          "module": "protobuf-java",
          "version": {
            "requires": "3.25.3"
          }
        },
        {
          "group": "com.google.protobuf",
          "module": "protobuf-java-util",
          "version": {
            "requires": "3.25.3"
          }
        },
        {
          "group": "androidx.activity",
          "module": "activity-ktx",
          "version": {
            "requires": "1.8.2"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.7.1"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-android",
          "version": {
            "requires": "1.7.3"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.6.0"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-viewmodel-ktx",
          "version": {
            "requires": "2.7.0"
          }
        },
        {
          "group": "androidx.work",
          "module": "work-runtime",
          "version": {
            "requires": "2.9.0"
          }
        },
        {
          "group": "androidx.work",
          "module": "work-runtime-ktx",
          "version": {
            "requires": "2.9.0"
          }
        },
        {
          "group": "com.google.dagger",
          "module": "dagger",
          "version": {
            "requires": "2.50"
          }
        },
        {
          "group": "com.github.skydoves",
          "module": "sandwich-retrofit",
          "version": {
            "requires": "2.0.6"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-reflect",
          "version": {
            "requires": "1.9.22"
          }
        },
        {
          "group": "org.mockito",
          "module": "mockito-bom",
          "version": {
            "requires": "5.11.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.9.22"
          }
        }
      ],
      "files": [
        {
          "name": "access-5.0.aar",
          "url": "access-5.0.aar",
          "size": 2819279,
          "sha512": "bba1a9d60a2d7dc2f695b08198c476b4c733688c3dfbbf1c3a12a167eebf3cb4fcbed4f4704dcbc680b9b330d79bce0be78307b9f79d9a5e7f1e768cc68c9b8c",
          "sha256": "ce9c1755d2b793e4f70df0928aebbcdfd1d6d6b6cf29c30cf03a045f14bfb4f8",
          "sha1": "664998562362344886ca10d23a6f25e437b84bd0",
          "md5": "943c28e26963facd5dee9e9c20699baf"
        }
      ]
    },
    {
      "name": "releaseSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "files": [
        {
          "name": "access-5.0-sources.jar",
          "url": "access-5.0-sources.jar",
          "size": 921868,
          "sha512": "2696c2fe9d115b77b0ecb7826020d1408c62309d5bebea56da5adfb7f2eaa4a702b548e7e2a54e8326e957f8493a072363c48d2d9378543f502547f4e476ca66",
          "sha256": "2a16b92f796d383a0dc539f3190316b913559b779c4ecd96d2246ad3b6752d4f",
          "sha1": "606a8d03203b23375137b987dcda6a1f9e4484e3",
          "md5": "113b0541640593615d7f3d0d8f5f697d"
        }
      ]
    }
  ]
}
